{ config, pkgs, ... }: {
  imports = [
    ./audio.nix
    ./browser.nix
    ./display-management.nix
    ./docker.nix
    ./flameshot.nix
    ./fonts.nix
    ./git.nix
    ./gtk.nix
    ./hibernate.nix
    ./hm-alias.nix
    ./nautilus.nix
    ./networking.nix
    ./notifications.nix
    ./nushell.nix
    ./nix-cli.nix
    ./password-manager.nix
    ./plymouth
    ./polkit.nix
    ./rofi
    ./screensharing.nix
    ./session.nix
    ./sway
    ./swaylock
    ./terminal.nix
    ./time.nix
    ./users.nix
    ./vscode.nix
    ./wdisplays.nix
    ./yubikey
    ./zsh
  ];
}
