{ config, pkgs, ... }: {
  imports = [
    ./audio.nix
    ./bootscreen
    ./browser.nix
    ./clipboard.nix
    ./display-manager.nix
    ./docker.nix
    ./file-manager.nix
    ./fonts.nix
    ./git.nix
    ./gtk.nix
    ./hibernate.nix
    ./launcher
    ./lockscreen
    ./file-manager.nix
    ./networking.nix
    ./notifications.nix
    ./shell.nix
    ./nix-cli.nix
    ./password-manager.nix
    ./privilige-manager.nix
    ./screensharing.nix
    ./screenshots.nix
    ./session.nix
    ./terminal.nix
    ./time.nix
    ./users.nix
    ./vscode.nix
    ./yubikey
    ./window-manager
  ];
}
